### PR TITLE
Added JavaScript string regex

### PR DESCRIPTION
**Pull request by niko-la-petrovic**
The existing JavaScript example provides a regex for properties of a JavaScript object, but not for a simple string, which I prefer.

If you'd like me to make any adjustments please let me know 👍

### CODE REVIEW

**Review by paolotiu — CHANGES_REQUESTED** [review]
Maybe the name could be "Javascript variable string" instead of just "Javascript string" to remove all ambiguities. Also, please add the section to the table of contents on the top of the README (After the "Plain Javascript Object"). 

Thank you so much!

**Comment by niko-la-petrovic** [comment]
No problem 👍 Will do.

**Comment by paolotiu** [comment]
Perfect! Thank you for this 🎉

**Comment by niko-la-petrovic** [comment]
Of course 👍 Thanks for the neat repo!

**Pull request merged**
